require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/**'
    - 'bin/**'
    - 'Gemfile.lock'
    - 'spec/fixtures/**'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
